03_Django/lecture3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet")
]

03_Django/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

03_Django/lecture3/newyear/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index")
]

03_Django/lecture3/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

03_Django/lecture3/hello/models.py
from django.db import models

# Create your models here.

03_Django/lecture3/newyear/models.py
from django.db import models

# Create your models here.

03_Django/lecture3/tasks/models.py
from django.db import models

# Create your models here.

03_Django/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")


def greet(request, name):
    return render(request, "hello/greet.html", {"name":name.capitalize()})

03_Django/lecture3/newyear/views.py
from django.shortcuts import render

import datetime
# Create your views here.
def index(request):
    now = datetime.datetime.now()

    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
        })

03_Django/lecture3/tasks/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms

# Create your views here.


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")




def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })



def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
            "form": form
            })
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

03_Django/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Greetings!</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

03_Django/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
    </body>
</html>

03_Django/lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>New Year</title>
        <link rel="stylesheet"  href="{% static 'newyear/style.css' %}">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

03_Django/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Add Task</h1>
        <form action="{% url 'tasks:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <a href="{% url 'tasks:index' %}">View tasks</a>
{% endblock %}

03_Django/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Tasks</h1>
        <ul>
            {% for task in tasks %}
                <li>{{task}}</li>
            {% empty %}
                <li>No tasks.</li>
            {% endfor %}
            <a href="{% url 'tasks:add' %}">Add new task</a>
        </ul>
{% endblock %}

03_Django/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>